### ISSUE TITLE
does not work with two elements

### ISSUE THREAD

**Issue by bwanaaa** [vvo/in-viewport#12]
I have an audio player that plays different songs depending on what's in the viewport. Here's a codepen:

http://codepen.io/littleredbowtie/pen/OyLMNq

It starts properly and switches to the the second song properly. But when I scroll back up to the top, it does not switch back to the first song.

Where's my error please?

Stefan

**Comment by vvo** [comment]
I don't know, can you do a simpler example without any song, audio etc? Just two elements and getting callbacks, then we can see what's wrong

**Comment by tzi** [comment]
We are here to help, but I will close this issue without further informations.

Cheers,
Thomas.
