### ISSUE TITLE
Test: detect element inserted in the DOM with MutationObserver 

### ISSUE THREAD

**Issue by tzi** [vvo/in-viewport#14]
Hello @vvo!

It's pretty annoying, that the result of the `MutationObserver` is aleatory.
I didn't succeed in fixing it, because it is beyond my skills.
But, here is my debug observation:

---

**1. Aleatory because of the failsafe**

There is a failsafe check with a `setInterval()` set to be activated every 150ms.
In the other side, the test waits 50ms to check if the `MutationObserver` was triggered.
That explains why the test only pass third of the time.

=> If we ask the test to wait for more than 200ms, it works all the time
=> If we remove the failsafe check, it fails all the time

---

**2. No idle time between the context set up and the test case**

The `MutationObserver` compare the mutated nodes with the watched nodes, so it does a new check only if a watched node has a mutation.
The watched nodes are set in the context set up, via an [asynchronous call](https://github.com/vvo/in-viewport/blob/master/in-viewport.js#L197).
This asynchronous call waits for idle time, and it happens only **after** the test ends.
So when the `MutationObserver` is triggered, the element is not currently watched.

The check is also called via an [asynchronous call](https://github.com/vvo/in-viewport/blob/master/in-viewport.js#L256) that can add a small delay.

=> If we remove this two tricks, the test pass all the time.

---

I hopes it helps.

Cheers,
Thomas.

**Comment by vvo** [comment]
thanks!! That's pretty messy indeed..

**Comment by vvo** [comment]
I removed the setTimeout around the remote.add and the tests are passing. I am sure there's a reason for this setTimeout but I would say let's remove it and wait.. :)

**Comment by vvo** [comment]
Tests are ok also on IE11 and this should be our next target browser now, stop wasting time!

**Comment by tzi** [comment]
Yes \o/
Thanks for the correction! That will improve the developer experience.

Is there a real cost of maintaining this code for IE9 or IE10?

**Comment by vvo** [comment]
> Is there a real cost of maintaining this code for IE9 or IE10?

I really dunno, but I think I will not want to care anymore! :D

**Comment by tzi** [comment]
I understand :)
