### ISSUE TITLE
Getting some sort of infinite loop/error with compareDocumentPosition

### ISSUE THREAD

**Issue by adamgins** [vvo/in-viewport#17]
Any ideas pls?
<img width="1219" alt="screen shot 2016-08-23 at 10 15 26 pm" src="https://cloud.githubusercontent.com/assets/7233741/17891448/2f69401a-697f-11e6-9aeb-862254af9abb.png">

**Comment by tzi** [comment]
Do you have any code to share?

**Comment by adamgins** [comment]
This is inside a Meteor `onRendered` which is equivalent to a `document.onReady`:

```
var self = this;

    var intialRender = true;

    self.autorun(function () {
        if (!Template.currentData()){
            return;
        }

        var elem = document.getElementById(self.data._id);


        inViewport(elem, visible);

        function visible(elt) {
            // elt === elem
            if (intialRender){
              //do something
                intialRender = false;
            }

        }


    })
```

I don't getthis error on my local server, only on the test server on the net

**Comment by adamgins** [comment]
I think I have this sorted. It was related to Meteor 

thanks for the quick response
