### ISSUE TITLE
Pros and cons of `in-viewport` and `react-waypoint`?

### ISSUE THREAD

**Issue by gy134340** [vvo/in-viewport#34]
hi, vvo, first, I think this is a great work of this lib, and I am working on detecting the dom is in the Viewport things.
also I found many other solutions, such as `react-waypoint` and `react-visible-sensor`, they all looks can do the same thing.

could you tell me what's the pros and cons of `in-viewport` and `react-waypoint`, or `waypoints `?
are they the same mechanism? which is better in different scene?

**Comment by vvo** [comment]
I have no idea sorry, take the one that works for you clearly

**Comment by gy134340** [comment]
@vvo  thank you, hope this lib better and better, I am using it now
